# Generated by Django 4.2.11 on 2025-11-09 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=64)),
                (
                    "bats",
                    models.CharField(
                        blank=True,
                        choices=[("R", "Right"), ("L", "Left"), ("S", "Switch")],
                        max_length=1,
                    ),
                ),
                (
                    "throws",
                    models.CharField(
                        blank=True,
                        choices=[("R", "Right"), ("L", "Left")],
                        max_length=1,
                    ),
                ),
                ("height_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("school", models.CharField(blank=True, max_length=128)),
                ("avatar_url", models.URLField(blank=True)),
                ("public_profile", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("fastball_velocity", "Fastball Velocity"),
                            ("exit_velocity", "Exit Velocity"),
                            ("pop_time", "Pop Time"),
                            ("sixty_yard_dash", "60 Yard Dash"),
                        ],
                        max_length=64,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("unit", models.CharField(default="", max_length=32)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="players.playerprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("profile", "metric_type")},
            },
        ),
    ]
